export const videos = {
    v: {
        1: {
            title: 'violett - tervist',
            subtitle: 'sisenemine kapslisse. admini intro. pikk lause.',
            videoUrl: 'http://167.71.52.104/violett_v01.mp4',
            subs: '',
            showLootBox: false,
            showQuiz: null,
            number: 1,
            quizTimestampInSeconds: null,
        },
        2: {
            title: 'violett - loot',
            subtitle: 'vaatame siis, mis me kaasa võtsime. ',
            videoUrl: 'http://167.71.52.104/violett_v02.mp4',
            showLootBox: true,
            showQuiz: null,
            quizTimestampInSeconds: null,
            number: 2,
        },
        3: {
            title: 'violett - elu kapslis',
            subtitle:
                'nüüd violett küsib teilt küsimusi. lorem ipsum dolor sit amet. kes lorem ipsumit peast teab?',
            videoUrl: 'http://167.71.52.104/violett_v03.mp4',
            showLootBox: false,
            showQuiz: '3.3 Elu kapslis - Violett',
            quizTimestampInSeconds: 3 * 60 + 10,
            number: 3,
        },
        4: {
            title: 'violett - videokõne',
            subtitle:
                'esimene videosild, kus kõik ütlevad tere ja soovivad teistele head.',
            videoUrl: 'http://167.71.52.104/violett_v01.mp4',
            showLootBox: false,
            number: 4,
        },
        5: {
            title: 'violett - esimene kõne',
            subtitle: 'violett on parim kapsel maailmas! eks?',
            videoUrl: 'https://vimeo.com/763941723',
            showLootBox: false,
            number: 5,
        },
        6: {
            title: 'violett - ajahüpe-video',
            subtitle: 'möödunud on esimene pikem periood',
            videoUrl: 'https://vimeo.com/763941723',
            showLootBox: false,
            number: 6,
        },
    },
    l: {
        1: {
            title: 'laim - tervist',
            subtitle: 'sisenemine kapslisse. admini intro. pikk lause.',
            videoUrl: 'http://167.71.52.104/laim_v01.mp4',
            subs: '',
            showLootBox: false,
            showQuiz: null,
            quizTimestampInSeconds: null,
            number: 1,
        },
        2: {
            title: 'laim - loot',
            subtitle: 'vaatame siis, mis me kaasa võtsime. ',
            videoUrl: 'http://167.71.52.104/laim_v02.mp4',
            showLootBox: true,
            showQuiz: null,
            quizTimestampInSeconds: null,
            number: 2,
        },
        3: {
            title: 'laim - elu kapslis',
            subtitle:
                'nüüd laim küsib teilt küsimusi. lorem ipsum dolor sit amet. kes lorem ipsumit peast teab?',
            videoUrl: 'http://167.71.52.104/laim_v03.mp4',
            showLootBox: false,
            showQuiz: '3.3 Elu kapslis - laim',
            quizTimestampInSeconds: null,
            number: 3,
        },
        4: {
            title: 'laim - videokõne',
            number: 4,
            subtitle:
                'esimene videosild, kus kõik ütlevad tere ja soovivad teistele head.',
            videoUrl: 'http://167.71.52.104/laim_v01.mp4',
            showLootBox: false,
        },
        5: {
            title: 'laim - esimene kõne',
            number: 5,
            subtitle: 'laim on parim kapsel maailmas! eks?',
            videoUrl: 'https://vimeo.com/763941723',
            showLootBox: false,
        },
        6: {
            title: 'laim - ajahüpe-video',
            subtitle: 'möödunud on esimene pikem periood',
            videoUrl: 'https://vimeo.com/763941723',
            showLootBox: false,
            number: 6,
        },
    },
    t: {
        1: {
            title: 'turkiis - tervist',
            subtitle: 'sisenemine kapslisse. admini intro. pikk lause.',
            videoUrl: 'http://167.71.52.104/turkiis_v01.mp4',
            subs: '',
            showLootBox: false,
            showQuiz: null,
            quizTimestampInSeconds: null,
            number: 1,
        },
        2: {
            title: 'turkiis - loot',
            subtitle: 'vaatame siis, mis me kaasa võtsime. ',
            videoUrl: 'http://167.71.52.104/turkiis_v02.mp4',
            showLootBox: true,
            showQuiz: null,
            quizTimestampInSeconds: null,
            number: 2,
        },
        3: {
            title: 'turkiis - elu kapslis',
            subtitle:
                'nüüd turkiis küsib teilt küsimusi. lorem ipsum dolor sit amet. kes lorem ipsumit peast teab?',
            videoUrl: 'http://167.71.52.104/turkiis_v03.mp4',
            showLootBox: false,
            showQuiz: '3.3 Elu kapslis - turkiis',
            quizTimestampInSeconds: null,
            number: 3,
        },
        4: {
            title: 'turkiis - videokõne',
            subtitle:
                'esimene videosild, kus kõik ütlevad tere ja soovivad teistele head.',
            videoUrl: 'http://167.71.52.104/turkiis_v01.mp4',
            showLootBox: false,
            number: 4,
        },
        5: {
            title: 'turkiis - esimene kõne',
            subtitle: 'turkiis on parim kapsel maailmas! eks?',
            videoUrl: 'https://vimeo.com/763941723',
            showLootBox: false,
            number: 5,
        },
        6: {
            title: 'turkiis - ajahüpe-video',
            subtitle: 'möödunud on esimene pikem periood',
            videoUrl: 'https://vimeo.com/763941723',
            showLootBox: false,
            number: 6,
        },
    },
    h: {
        1: {
            title: 'hobevalge - tervist',
            subtitle: 'sisenemine kapslisse. admini intro. pikk lause.',
            videoUrl: 'http://167.71.52.104/hobevalge_v01.mp4',
            subs: '',
            showLootBox: false,
            showQuiz: null,
            quizTimestampInSeconds: null,
            number: 1,
        },
        2: {
            title: 'hobevalge - loot',
            subtitle: 'vaatame siis, mis me kaasa võtsime. ',
            videoUrl: 'http://167.71.52.104/hobevalge_v02.mp4',
            showLootBox: true,
            showQuiz: null,
            quizTimestampInSeconds: null,
            number: 2,
        },
        3: {
            title: 'hobevalge - elu kapslis',
            subtitle:
                'nüüd hobevalge küsib teilt küsimusi. lorem ipsum dolor sit amet. kes lorem ipsumit peast teab?',
            videoUrl: 'http://167.71.52.104/hobevalge_v03.mp4',
            showLootBox: false,
            showQuiz: '3.3 Elu kapslis - hobevalge',
            quizTimestampInSeconds: null,
            number: 3,
        },
        4: {
            title: 'hobevalge - videokõne',
            subtitle:
                'esimene videosild, kus kõik ütlevad tere ja soovivad teistele head.',
            videoUrl: 'http://167.71.52.104/hobevalge_v01.mp4',
            showLootBox: false,
            number: 4,
        },
        5: {
            title: 'hobevalge - esimene kõne',
            subtitle: 'hobevalge on parim kapsel maailmas! eks?',
            videoUrl: 'https://vimeo.com/763941723',
            showLootBox: false,
            number: 5,
        },
        6: {
            title: 'hobevalge - ajahüpe-video',
            subtitle: 'möödunud on esimene pikem periood',
            videoUrl: 'https://vimeo.com/763941723',
            showLootBox: false,
            number: 6,
        },
    },
};
