export const videos = {
    v: {
        1: {
            title: '(violett/kõigil sama) admini intro',
            subtitle: 'sisenemine kapslisse. admini intro',
            videoUrl: 'http://167.71.52.104/violett/violett_v01.mp4',
            subs: '',
            showLootBox: false,
            showQuiz: null,
            number: 1,
            quizTimestampInSeconds: null,
            autoplay: true,
        },
        2: {
            title: 'violett: tere tulemast',
            subtitle: 'violett ütleb samuti oma tervitussõnad.',
            videoUrl: 'http://167.71.52.104/violett/violett_v02.mp4',
            showLootBox: false,
            showQuiz: null,
            quizTimestampInSeconds: null,
            number: 2,
            autoplay: true,
        },
        3: {
            title: 'violett - loot',
            subtitle:
                'vaatame siis, mis me kaasa võtsime. (näitab loot akent kapsli kohta)',
            videoUrl: 'http://167.71.52.104/violett/violett_v03.mp4',
            showLootBox: true,
            showQuiz: null,
            quizTimestampInSeconds: null,
            autoplay: true,
            number: 3,
        },
        4: {
            title: 'violett - elu kapslis',
            subtitle:
                'violett kirjeldab oma eesmärke ja elu värki kapslis. video lõpus avaneb statistikaküsitlus.',
            videoUrl: 'http://167.71.52.104/violett/violett_v04.mp4',
            showLootBox: false,
            showQuiz: '3.3 Elu kapslis - Violett',
            quizTimestampInSeconds: 60 + 42,
            autoplay: true,
            number: 4,
        },
        5: {
            title: '(violett/kõigil sama) zoom',
            subtitle:
                'esimene videosild, kus kõik ütlevad tere ja soovivad teistele head.',
            videoUrl: 'http://167.71.52.104/videokone1.mp4',
            showLootBox: false,
            showQuiz: null,
            quizTimestampInSeconds: null,
            autoplay: true,
            number: 5,
        },
        6: {
            title: 'violett - esimene kõne',
            subtitle:
                'violett on parim kapsel maailmas! eks? video lõpus peab audiitor kapteni käitumist hindama.',
            videoUrl: 'http://167.71.52.104/violett/violett_v05.mp4',
            showLootBox: false,
            showQuiz: '1. Audiitor',
            quizTimestampInSeconds: 3 * 60 + 34,
            autoplay: true,
            number: 6,
        },
        7: {
            title: '(violett/kõigil sama) - ajahüpe 1',
            subtitle: 'möödunud on esimene pikem periood. admini voiceover.',
            videoUrl: 'http://167.71.52.104/ajahype_01.mp4',
            showLootBox: false,
            autoplay: true,
            number: 7,
            showQuiz: null,
            quizTimestampInSeconds: null,
        },
        8: {
            title: '(violett/kõigil sama) - zoom 2',
            subtitle: 'zoomis raagitakse! juhuu.',
            videoUrl: 'http://167.71.52.104/videokone2.mp4',
            showLootBox: false,
            autoplay: true,
            number: 8,
            showQuiz: null,
            quizTimestampInSeconds: null,
        },
        9: {
            title: 'violett - k6ne',
            subtitle:
                '"me võiks siis mõelda, kui praktilised ja vajalikud need videokõned on...." -> lõpetab sõnadega "ma teen ettepaneku"',
            videoUrl: 'http://167.71.52.104/violett/violett_v06.mp4',
            showLootBox: false,
            autoplay: true,
            number: 9,
            showQuiz: null,
            quizTimestampInSeconds: null,
        },
        10: {
            title: 'inimestele eraldatava ressursihulga võiks siduda laste arvuga: tulemused',
            subtitle: 'hääletus avanes selle video alguses',
            videoUrl: 'http://167.71.52.104/violett/violett_v07.mp4',
            showLootBox: false,
            autoplay: true,
            number: 10,
            showQuiz: '3.8 I maailmavaateline hääletus - Violett',
            quizTimestampInSeconds: 0,
        },
        11: {
            title: '(violett/kõigil sama) - ajahype 2',
            subtitle: 'mitu aastat see nüüd oli?',
            videoUrl: 'http://167.71.52.104/ajahype_02.mp4',
            showLootBox: false,
            autoplay: true,
            number: 11,
            showQuiz: null,
            quizTimestampInSeconds: null,
        },
        12: {
            title: '(violett/kõigil sama) - zoom 3',
            subtitle: 'videokõne',
            videoUrl: 'http://167.71.52.104/videokone3.mp4',
            showLootBox: false,
            autoplay: true,
            number: 12,
            showQuiz: null,
            quizTimestampInSeconds: null,
        },
        13: {
            title: 'violett - k6ne',
            subtitle:
                'kapten laidab teisi kapsleid + teise suure hääletuse intro ',
            videoUrl: 'http://167.71.52.104/violett/violett_v08.mp4',
            showLootBox: false,
            autoplay: true,
            number: 13,
            showQuiz: null,
            quizTimestampInSeconds: null,
        },
        14: {
            title: 'violett - vallalised inimesed kaotavad hääletusõiguse? tulemused.',
            subtitle: 'video algab haaletusega audiitorile extreme kysimus',
            videoUrl: 'http://167.71.52.104/violett/violett_v09.mp4',
            showLootBox: false,
            autoplay: true,
            number: 14,
            showQuiz: '3.11 radikaalne süüdi kõne - Violett',
            quizTimestampInSeconds: 0,
        },
        15: {
            title: 'violett - agendi saatus',
            subtitle:
                'video algab hääletusega audiitorile agendi saatuse kohta',
            videoUrl: 'http://167.71.52.104/violett/violett_v10.mp4',
            showLootBox: false,
            autoplay: true,
            number: 15,
            showQuiz: '3.12 - Agendi saatus - Violett',
            quizTimestampInSeconds: 0,
        },
        16: {
            title: 'violett - "tulevik kuulub traditsioonidele"',
            subtitle:
                'video lõpus küsitakse audiitorilt, kuidas ta nüüd kapteni käitumist hindab',
            videoUrl: 'http://167.71.52.104/violett/violett_v11.mp4',
            showLootBox: false,
            autoplay: true,
            number: 16,
            showQuiz: '2. Audiitor',
            quizTimestampInSeconds: 100,
        },
        17: {
            title: '(violett/kõigil sama) ajahype 3',
            subtitle: '',
            videoUrl: 'http://167.71.52.104/ajahype_03.mp4',
            showLootBox: false,
            autoplay: true,
            number: 17,
            showQuiz: null,
            quizTimestampInSeconds: null,
        },
        18: {
            title: '(violett/kõigil sama) zoom 4',
            subtitle: '',
            videoUrl: 'http://167.71.52.104/videokone4.mp4',
            showLootBox: false,
            autoplay: true,
            number: 18,
            showQuiz: null,
            quizTimestampInSeconds: null,
        },
        19: {
            title: 'violett - video 12',
            subtitle:
                '"meid ei murra miski" chant lõpus -> admin sekkub ning käsib oma telefone vaadata.',
            videoUrl: 'http://167.71.52.104/violett/violett_v12.mp4',
            showLootBox: false,
            autoplay: true,
            number: 19,
            showQuiz: null,
            quizTimestampInSeconds: null,
        },
        20: {
            title: 'violett: kas kukutad kapteni? tulemuste lugemine',
            subtitle:
                'kapteni 6hutusk6ne. admin sekkub voiceoveriga ja kysib hobevalgete saatuse kohta. ' +
                'video lõpupoole hakkab häiresignaal. inimesed tõusevad püsti',
            videoUrl: 'http://167.71.52.104/violett/violett_v13.mp4',
            showLootBox: false,
            autoplay: true,
            number: 20,
            showQuiz: '3.16 - Kapteni kukutamine - Violett',
            quizTimestampInSeconds: 0,
        },
        21: {
            title: 'violett- video 14',
            subtitle: 'finaal. inimesed valjuvad',
            videoUrl: '',
            showLootBox: false,
            autoplay: true,
            number: 21,
            showQuiz: null,
            quizTimestampInSeconds: null,
        },
    },
    t: {
        1: {
            title: 'türkiis - admini intro',
            subtitle: 'sisenemine kapslisse. admini intro. pikk lause.',
            videoUrl: 'http://167.71.52.104/tyrkiis/tyrkiis_v01.mp4',
            subs: '',
            showLootBox: false,
            showQuiz: null,
            number: 1,
            quizTimestampInSeconds: null,
            autoplay: true,
        },
        2: {
            title: 'türkiis - tere tulemast',
            subtitle: 'vaatame siis, mis me kaasa võtsime. ',
            videoUrl: 'http://167.71.52.104/tyrkiis/tyrkiis_v02.mp4',
            showLootBox: false,
            showQuiz: null,
            quizTimestampInSeconds: null,
            number: 2,
            autoplay: true,
        },
        3: {
            title: 'türkiis - loot',
            subtitle: 'dfsbxvc ',
            videoUrl: 'http://167.71.52.104/tyrkiis/tyrkiis_v03.mp4',
            showLootBox: true,
            showQuiz: null,
            quizTimestampInSeconds: null,
            autoplay: true,
            number: 3,
        },
        4: {
            title: 'türkiis - elu kapslis',
            subtitle:
                'nüüd Türkiis küsib teilt küsimusi. käib pharrelli happy. jne',
            videoUrl: 'http://167.71.52.104/tyrkiis/tyrkiis_v04.mp4',
            showLootBox: false,
            showQuiz: '3.3 Elu kapslis - Türkiis',
            quizTimestampInSeconds: 60 + 42,
            autoplay: true,
            number: 4,
        },
        5: {
            title: '(türkiis/kõigil sama) zoom',
            subtitle:
                'esimene videosild, kus kõik ütlevad tere ja soovivad teistele head.',
            videoUrl: 'http://167.71.52.104/videokone1.mp4',
            showLootBox: false,
            showQuiz: null,
            quizTimestampInSeconds: null,
            autoplay: true,
            number: 5,
        },
        6: {
            title: 'türkiis - esimene kõne',
            subtitle: 'Türkiis on parim kapsel maailmas! eks?',
            videoUrl: 'http://167.71.52.104/tyrkiis/tyrkiis_v05.mp4',
            showLootBox: false,
            showQuiz: '1. Audiitor',
            quizTimestampInSeconds: 3 * 60 + 34,
            autoplay: true,
            number: 6,
        },
        7: {
            title: '(türkiis/kõigil sama) - ajahüpe-video',
            subtitle: 'möödunud on esimene pikem periood',
            videoUrl: 'http://167.71.52.104/ajahype_01.mp4',
            showLootBox: false,
            autoplay: true,
            number: 7,
            showQuiz: null,
            quizTimestampInSeconds: null,
        },
        8: {
            title: '(türkiis/kõigil sama) - zoom 2',
            subtitle: 'zoomis raagitakse',
            videoUrl: 'http://167.71.52.104/videokone2.mp4',
            showLootBox: false,
            autoplay: true,
            number: 8,
            showQuiz: null,
            quizTimestampInSeconds: null,
        },
        9: {
            title: 'türkiis - k6ne',
            subtitle: 'kapten teeb ettepanekuid',
            videoUrl: 'http://167.71.52.104/tyrkiis/tyrkiis_v06.mp4',
            showLootBox: false,
            autoplay: true,
            number: 9,
            showQuiz: null,
            quizTimestampInSeconds: null,
        },
        10: {
            title: 'türkiis -video 7  k6ne',
            subtitle: 'kapten mmhh teeb ettepanekuid, k6ne',
            videoUrl: 'http://167.71.52.104/tyrkiis/tyrkiis_v07.mp4',
            showLootBox: false,
            autoplay: true,
            number: 10,
            showQuiz: '3.8 I maailmavaateline hääletus - Türkiis',
            quizTimestampInSeconds: 0,
        },
        11: {
            title: '(türkiis/kõigil sama) ajahype',
            subtitle: 'möödunud on X aastat...',
            videoUrl: 'http://167.71.52.104/ajahype_02.mp4',
            showLootBox: false,
            autoplay: true,
            number: 11,
            showQuiz: null,
            quizTimestampInSeconds: null,
        },
        12: {
            title: '(türkiis/kõigil sama) zoom',
            subtitle: 'mingi zoom jälle',
            videoUrl: 'http://167.71.52.104/videokone3.mp4',
            showLootBox: false,
            autoplay: true,
            number: 12,
            showQuiz: null,
            quizTimestampInSeconds: null,
        },
        13: {
            title: 'türkiis -sdfgdb  k6ne',
            subtitle:
                'kapten laidab teisi kapsleid + teise suure haaletuse intro ',
            videoUrl: 'http://167.71.52.104/tyrkiis/tyrkiis_v08.mp4',
            showLootBox: false,
            autoplay: true,
            number: 13,
            showQuiz: null,
            quizTimestampInSeconds: null,
        },
        14: {
            title: 'türkiis -video algab haaletusega -> extreme kysimus',
            subtitle: 'noh mdea. Mihkel, kirjeldusi?',
            videoUrl: 'http://167.71.52.104/tyrkiis/tyrkiis_v09.mp4',
            showLootBox: false,
            autoplay: true,
            number: 14,
            showQuiz: '3.11 radikaalne süüdi kõne - Türkiis',
            quizTimestampInSeconds: 0,
        },
        15: {
            title: 'türkiis -video algab haaletusega -> agendi saatus',
            subtitle: 'kapten mmhh teeb ettepanekuid, k6ne',
            videoUrl: 'http://167.71.52.104/tyrkiis/tyrkiis_v10.mp4',
            showLootBox: false,
            autoplay: true,
            number: 15,
            showQuiz: '3.12 - Agendi saatus - Türkiis',
            quizTimestampInSeconds: 0,
        },
        16: {
            title: 'türkiis - -suur k6ne',
            subtitle: 'video lopus on quiz audiitorile',
            videoUrl: 'http://167.71.52.104/violett/violett_v11.mp4',
            showLootBox: false,
            autoplay: true,
            number: 16,
            showQuiz: '2. Audiitor',
            quizTimestampInSeconds: 100,
        },
        17: {
            title: '(türkiis/kõigil sama) - ajahype 3',
            subtitle: '',
            videoUrl: 'http://167.71.52.104/ajahype_03.mp4',
            showLootBox: false,
            autoplay: true,
            number: 17,
            showQuiz: null,
            quizTimestampInSeconds: null,
        },
        18: {
            title: '(türkiis/kõigil sama) - zoom 4',
            subtitle: '',
            videoUrl: 'http://167.71.52.104/videokone4.mp4',
            showLootBox: false,
            autoplay: true,
            number: 18,
            showQuiz: null,
            quizTimestampInSeconds: null,
        },
        19: {
            title: 'türkiis- video 12',
            subtitle: '',
            videoUrl: 'http://167.71.52.104/tyrkiis/tyrkiis_v12.mp4',
            showLootBox: false,
            autoplay: true,
            number: 19,
            showQuiz: null,
            quizTimestampInSeconds: null,
        },
        20: {
            title: 'türkiis - video 13',
            subtitle:
                'kapteni 6hutusk6ne. admin sekkub voiceoveriga ja kysib hobevalgete saatuse kohta',
            videoUrl: 'http://167.71.52.104/tyrkiis/tyrkiis_v13.mp4',
            showLootBox: false,
            autoplay: true,
            number: 20,
            showQuiz: '3.16 - Kapteni kukutamine - Türkiis',
            quizTimestampInSeconds: 0,
        },
        21: {
            title: 'türkiis - video 14',
            subtitle: 'finaal. inimesed valjuvad',
            videoUrl: '',
            showLootBox: false,
            autoplay: true,
            number: 21,
            showQuiz: null,
            quizTimestampInSeconds: null,
        },
    },
    l: {
        1: {
            title: 'laimi admini intro',
            subtitle: 'laimi videosid pole serveris',
            videoUrl: '',
            subs: '',
            showLootBox: false,
            autoplay: true,
            showQuiz: null,
            quizTimestampInSeconds: null,
            number: 1,
        },
    },
    h: {
        1: {
            title: 'hobevalge admini intro',
            subtitle: 'hobevalge videosid pole serveris',
            videoUrl: '',
            subs: '',
            showLootBox: false,
            autoplay: true,
            showQuiz: null,
            quizTimestampInSeconds: null,
            number: 1,
        },
    },
};
