export const videos = {
    v: {
        1: {
            title: 'violett - admini intro',
            subtitle: 'sisenemine kapslisse. admini intro. pikk lause.',
            videoUrl: 'http://167.71.52.104/violett_v01.mp4',
            subs: '',
            showLootBox: false,
            showQuiz: null,
            number: 1,
            quizTimestampInSeconds: null,
            autoplay: true,
        },
        2: {
            title: 'violett - tere tulemast',
            subtitle: 'vaatame siis, mis me kaasa võtsime. ',
            videoUrl: 'http://167.71.52.104/violett_v02.mp4',
            showLootBox: false,
            showQuiz: null,
            quizTimestampInSeconds: null,
            number: 2,
            autoplay: true,
        },
        3: {
            title: 'violett - loot',
            subtitle: 'dfsbxvc ',
            videoUrl: 'http://167.71.52.104/violett_v03.mp4',
            showLootBox: true,
            showQuiz: null,
            quizTimestampInSeconds: null,
            autoplay: true,
            number: 3,
        },
        4: {
            title: 'violett - elu kapslis',
            subtitle:
                'nüüd violett küsib teilt küsimusi. lorem ipsum dolor sit amet. kes lorem ipsumit peast teab?',
            videoUrl: 'http://167.71.52.104/violett_v04.mp4',
            showLootBox: false,
            showQuiz: '3.3 Elu kapslis - Violett',
            quizTimestampInSeconds: 60 + 42,
            autoplay: true,
            number: 4,
        },
        5: {
            title: '(violett) zoom',
            subtitle:
                'esimene videosild, kus kõik ütlevad tere ja soovivad teistele head.',
            videoUrl: 'videokone',
            showLootBox: false,
            showQuiz: null,
            quizTimestampInSeconds: null,
            autoplay: true,
            number: 5,
        },
        6: {
            title: 'violett - esimene kõne',
            subtitle: 'violett on parim kapsel maailmas! eks?',
            videoUrl: 'http://167.71.52.104/violett_v05.mp4',
            showLootBox: false,
            showQuiz: '1. Audiitor',
            quizTimestampInSeconds: 3 * 60 + 34,
            autoplay: true,
            number: 6,
        },
        7: {
            title: 'violett - ajahüpe-video',
            subtitle: 'möödunud on esimene pikem periood',
            videoUrl: 'https://vimeo.com/763941723',
            showLootBox: false,
            autoplay: true,
            number: 7,
            showQuiz: null,
            quizTimestampInSeconds: null,
        },
        8: {
            title: 'violett - zoom 2',
            subtitle: 'zoomis raagitakse',
            videoUrl: 'https://vimeo.com/763941723',
            showLootBox: false,
            autoplay: true,
            number: 8,
            showQuiz: null,
            quizTimestampInSeconds: null,
        },
        9: {
            title: 'violett - k6ne',
            subtitle:
                'kapten teeb ettepanekuid. mis see ettepanekute popup on?',
            videoUrl: 'http://167.71.52.104/violett_v06.mp4',
            showLootBox: false,
            autoplay: true,
            number: 9,
            showQuiz: null,
            quizTimestampInSeconds: null,
        },
        10: {
            title: 'violett -video 7  k6ne',
            subtitle: 'kapten mmhh teeb ettepanekuid, k6ne',
            videoUrl: 'http://167.71.52.104/violett_v07.mp4',
            showLootBox: false,
            autoplay: true,
            number: 10,
            showQuiz: '3.8 I maailmavaateline hääletus - Violett',
            quizTimestampInSeconds: 0,
        },
        11: {
            title: 'violett ajahype',
            subtitle: 'kapten mmhh teeb ettepanekuid, k6ne',
            videoUrl: '',
            showLootBox: false,
            autoplay: true,
            number: 11,
            showQuiz: null,
            quizTimestampInSeconds: null,
        },
        12: {
            title: 'violett zoom',
            subtitle: 'kapten mmhh teeb ettepanekuid, k6ne',
            videoUrl: '',
            showLootBox: false,
            autoplay: true,
            number: 12,
            showQuiz: null,
            quizTimestampInSeconds: null,
        },
        13: {
            title: 'violett -sdfgdb  k6ne',
            subtitle:
                'kapten laidab teisi kapsleid + teise suure haaletuse intro ',
            videoUrl: 'http://167.71.52.104/violett_v08.mp4',
            showLootBox: false,
            autoplay: true,
            number: 13,
            showQuiz: null,
            quizTimestampInSeconds: null,
        },
        14: {
            title: 'violett -video algab haaletusega extreme kysimus',
            subtitle: 'kapten mmhh teeb ettepanekuid, k6ne',
            videoUrl: 'http://167.71.52.104/violett_v09.mp4',
            showLootBox: false,
            autoplay: true,
            number: 14,
            showQuiz: '3.11 radikaalne süüdi kõne - Violett',
            quizTimestampInSeconds: 0,
        },
        15: {
            title: 'violett -video algab haaletusega agendi saatus',
            subtitle: 'kapten mmhh teeb ettepanekuid, k6ne',
            videoUrl: 'http://167.71.52.104/violett_v10.mp4',
            showLootBox: false,
            autoplay: true,
            number: 15,
            showQuiz: '3.12 - Agendi saatus - Violett',
            quizTimestampInSeconds: 0,
        },
        16: {
            title: 'violett- -suur k6ne',
            subtitle: 'video lopus onquiz',
            videoUrl: 'http://167.71.52.104/violett_v11.mp4',
            showLootBox: false,
            autoplay: true,
            number: 16,
            showQuiz: '2. Audiitor',
            quizTimestampInSeconds: 100,
        },
        17: {
            title: 'violett- ajahype 3',
            subtitle: '',
            videoUrl: '',
            showLootBox: false,
            autoplay: true,
            number: 17,
            showQuiz: null,
            quizTimestampInSeconds: null,
        },
        18: {
            title: 'violett- zoom 4',
            subtitle: '',
            videoUrl: '',
            showLootBox: false,
            autoplay: true,
            number: 18,
            showQuiz: null,
            quizTimestampInSeconds: null,
        },
        19: {
            title: 'violett- video 12',
            subtitle: '',
            videoUrl: 'http://167.71.52.104/violett_v12.mp4',
            showLootBox: false,
            autoplay: true,
            number: 19,
            showQuiz: null,
            quizTimestampInSeconds: null,
        },
        20: {
            title: 'violett- video 13',
            subtitle:
                'kapteni 6hutusk6ne. admin sekkub voiceoveriga ja kysib hobevalgete saatuse kohta',
            videoUrl: 'http://167.71.52.104/violett_v13.mp4',
            showLootBox: false,
            autoplay: true,
            number: 20,
            showQuiz: '3.16 - Kapteni kukutamine - Violett',
            quizTimestampInSeconds: 0,
        },
        21: {
            title: 'violett- video 14',
            subtitle: 'finaal. inimesed valjuvad',
            videoUrl: '',
            showLootBox: false,
            autoplay: true,
            number: 21,
            showQuiz: null,
            quizTimestampInSeconds: null,
        },
    },
    l: {
        1: {
            title: 'laim - tervist',
            subtitle: 'sisenemine kapslisse. admini intro. pikk lause.',
            videoUrl: 'http://167.71.52.104/laim_v01.mp4',
            subs: '',
            showLootBox: false,
            autoplay: true,
            showQuiz: null,
            quizTimestampInSeconds: null,
            number: 1,
        },
        2: {
            title: 'laim - loot',
            subtitle: 'vaatame siis, mis me kaasa võtsime. ',
            videoUrl: 'http://167.71.52.104/laim_v02.mp4',
            showLootBox: true,
            showQuiz: null,
            autoplay: true,
            quizTimestampInSeconds: null,
            number: 2,
        },
        3: {
            title: 'laim - elu kapslis',
            subtitle:
                'nüüd laim küsib teilt küsimusi. lorem ipsum dolor sit amet. kes lorem ipsumit peast teab?',
            videoUrl: 'http://167.71.52.104/laim_v03.mp4',
            showLootBox: false,
            showQuiz: '3.3 Elu kapslis - Laim',
            autoplay: true,
            quizTimestampInSeconds: 3 * 60,
            number: 3,
        },
        4: {
            title: 'laim - videokõne',
            number: 4,
            subtitle:
                'esimene videosild, kus kõik ütlevad tere ja soovivad teistele head.',
            videoUrl: 'http://167.71.52.104/laim_v01.mp4',
            autoplay: true,
            showLootBox: false,
            showQuiz: null,
            quizTimestampInSeconds: null,
        },
        5: {
            title: 'laim - esimene kõne',
            number: 5,
            subtitle: 'laim on parim kapsel maailmas! eks?',
            videoUrl: 'https://vimeo.com/763941723',
            autoplay: true,
            showLootBox: false,
            showQuiz: null,
            quizTimestampInSeconds: null,
        },
        6: {
            title: 'laim - ajahüpe-video',
            subtitle: 'möödunud on esimene pikem periood',
            videoUrl: 'https://vimeo.com/763941723',
            showLootBox: false,
            autoplay: true,
            number: 6,
            showQuiz: null,
            quizTimestampInSeconds: null,
        },
    },
    t: {
        1: {
            title: 'turkiis - tervist',
            subtitle: 'sisenemine kapslisse. admini intro. pikk lause.',
            videoUrl: 'http://167.71.52.104/turkiis_v01.mp4',
            subs: '',
            showLootBox: false,
            showQuiz: null,
            quizTimestampInSeconds: null,
            autoplay: true,
            number: 1,
        },
        2: {
            title: 'turkiis - loot',
            subtitle: 'vaatame siis, mis me kaasa võtsime. ',
            videoUrl: 'http://167.71.52.104/turkiis_v02.mp4',
            showLootBox: true,
            showQuiz: null,
            quizTimestampInSeconds: null,
            autoplay: true,
            number: 2,
        },
        3: {
            title: 'turkiis - elu kapslis',
            subtitle:
                'nüüd turkiis küsib teilt küsimusi. lorem ipsum dolor sit amet. kes lorem ipsumit peast teab?',
            videoUrl: 'http://167.71.52.104/turkiis_v03.mp4',
            showLootBox: false,
            showQuiz: '3.3 Elu kapslis - Türkiis',
            quizTimestampInSeconds: 3 * 60,
            autoplay: true,
            number: 3,
        },
        4: {
            title: 'turkiis - videokõne',
            subtitle:
                'esimene videosild, kus kõik ütlevad tere ja soovivad teistele head.',
            videoUrl: 'http://167.71.52.104/turkiis_v01.mp4',
            autoplay: true,
            showLootBox: false,
            number: 4,
            showQuiz: null,
            quizTimestampInSeconds: null,
        },
        5: {
            title: 'turkiis - esimene kõne',
            subtitle: 'turkiis on parim kapsel maailmas! eks?',
            videoUrl: 'https://vimeo.com/763941723',
            showLootBox: false,
            autoplay: true,
            number: 5,
            showQuiz: null,
            quizTimestampInSeconds: null,
        },
        6: {
            title: 'turkiis - ajahüpe-video',
            subtitle: 'möödunud on esimene pikem periood',
            videoUrl: 'https://vimeo.com/763941723',
            showLootBox: false,
            autoplay: true,
            number: 6,
            showQuiz: null,
            quizTimestampInSeconds: null,
        },
    },
    h: {
        1: {
            title: 'hobevalge - tervist',
            subtitle: 'sisenemine kapslisse. admini intro. pikk lause.',
            videoUrl: 'http://167.71.52.104/hobevalge_v01.mp4',
            subs: '',
            showLootBox: false,
            showQuiz: null,
            quizTimestampInSeconds: null,
            autoplay: true,
            number: 1,
        },
        2: {
            title: 'hobevalge - loot',
            subtitle: 'vaatame siis, mis me kaasa võtsime. ',
            videoUrl: 'http://167.71.52.104/hobevalge_v02.mp4',
            showLootBox: true,
            showQuiz: null,
            autoplay: true,
            quizTimestampInSeconds: null,
            number: 2,
        },
        3: {
            title: 'hobevalge - elu kapslis',
            subtitle:
                'nüüd hobevalge küsib teilt küsimusi. lorem ipsum dolor sit amet. kes lorem ipsumit peast teab?',
            videoUrl: 'http://167.71.52.104/hobevalge_v03.mp4',
            showLootBox: false,
            showQuiz: '3.3 Elu kapslis - Hõbevalge',
            quizTimestampInSeconds: 3 * 60,
            autoplay: true,
            number: 3,
        },
        4: {
            title: 'hobevalge - videokõne',
            subtitle:
                'esimene videosild, kus kõik ütlevad tere ja soovivad teistele head.',
            videoUrl: 'http://167.71.52.104/hobevalge_v01.mp4',
            autoplay: true,
            showLootBox: false,
            number: 4,
            showQuiz: null,
            quizTimestampInSeconds: null,
        },
        5: {
            title: 'hobevalge - esimene kõne',
            subtitle: 'hobevalge on parim kapsel maailmas! eks?',
            videoUrl: 'https://vimeo.com/763941723',
            showLootBox: false,
            autoplay: true,
            number: 5,
            showQuiz: null,
            quizTimestampInSeconds: null,
        },
        6: {
            title: 'hobevalge - ajahüpe-video',
            subtitle: 'möödunud on esimene pikem periood',
            videoUrl: 'https://vimeo.com/763941723',
            showLootBox: false,
            autoplay: true,
            number: 6,
            showQuiz: null,
            quizTimestampInSeconds: null,
        },
    },
};
